language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
install:
    - python setup.py install
    - pip install -r tests_require.txt
script:
    - python setup.py test
after_success:
    coveralls
