language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
install:
    - python setup.py install
    - pip install -r tests_require.txt
    - pip install python-coveralls
script:
    - python setup.py test
after_success:
    coveralls
